apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ng2a
  name: ng2a
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ng2a
  template:
    metadata:
      labels:
        app: ng2a
    spec:
      containers:
      - image: nginx
        name: nginx
